name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            config: Release
          - kind: windows
            os: windows-latest
            target: win-x64
            config: Release
          - kind: macOS
            os: macos-15
            target: osx-arm64
            config: Release
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore /p:Configuration=${{ matrix.config }}
    - name: Publish TACTTool
      run: dotnet publish --configuration ${{ matrix.config }} --no-restore --self-contained TACTTool/TACTTool.csproj
    - name: Publish TACTSharp
      run: dotnet publish --configuration ${{ matrix.config }} --no-restore TACTSharp/TACTSharp.csproj
    - name: Test
      run: dotnet test --verbosity normal
    - name: Archive TACTTool Release
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/TACTTool/bin/Release/net10.0/${{ matrix.target }}/publish
        type: 'zip'
        filename: ${{ github.workspace }}/TACTTool-${{ matrix.config }}-${{ matrix.target }}.zip
    - name: Archive TACTSharp Release
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/TACTSharp/bin/Release/net10.0/publish
        type: 'zip'
        filename: ${{ github.workspace }}/TACTSharp-lib-${{ matrix.config }}-${{ matrix.target }}.zip
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        files: |
            ${{ github.workspace }}/TACTTool-${{ matrix.config }}-${{ matrix.target }}.zip
            ${{ github.workspace }}/TACTSharp-lib-${{ matrix.config }}-${{ matrix.target }}.zip
